### ISSUE TITLE
Archive does not compile

### ISSUE THREAD

**Issue by cjwetherington** [yazhao/PSU_Thesis#1]
Hello.  I'm a bit confused about how this archive is supposed to be used.  The folder structure seems to have been flattened out; e.g. the content referenced in https://github.com/yazhao/PSU_Thesis/blob/main/Chapter-1 is not available in this archive—folders have been rendered here as text files containing path references for files that are unreachable.  I assume this is not intentional.

I can confirm that the main .tex file doesn't compile owing to the absence of the directory architecture and underlying files.  I can try to fix this via a PR if desired.  Also willing to host the archive via Penn State Research Informatics' Git space if that's of interest.

**Comment by yazhao** [comment]
I truly apologize for the delay in answering this issue: I need to set this up so I get notified about issues by email.

The long and short of it is that the copy of the thesis template .zip file that I had asked from a friend was not complete, and instead of having the actual folders only had the links to the folders, which I put in this repository. I've taken the template from Overleaf, which as far as I know is otherwise identical to the last updated version, and have replaced all previous files with the proper ones from the Overleaf.

This should now compile as intended. I'll also reach out privately about hosting this archive elsewhere.
