### ISSUE TITLE
Bibliography in alphabetical order

### ISSUE THREAD

**Issue by ayaeide** [yazhao/PSU_Thesis#4]
Hello. I'm using this template, but I have a question about sorting in the bibliography. I would like to sort it alphabetically, and when I tried adding a sorting function in the bst file, it didn't work. Additionally, when I added "\bibliographystyle{plain}" in the tex file, it messed up the current APA format. This template seems to have citations ordered by the order they appear in the text, but could you please kindly inform about where the sorting is being controlled?

**Comment by yazhao** [comment]
Hi there,

I'm honestly not sure where the sorting is being controlled: I went back to my own dissertation files and it looks like I simply used a different .bst file and referenced that rather than the default .bst in the YourName-Dissertation.tex section. The .bst file I used can be found here: https://ftp.math.utah.edu/pub/tex/bibtex/agsm.bst
